# Generated by Django 5.0.4 on 2024-05-01 22:38

import django.db.models.deletion
import djangoapp.common.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeCaseDefectModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(djangoapp.common.models.GenericEntityBase, models.Model),
        ),
        migrations.CreateModel(
            name='LifeCaseModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('cito', models.BooleanField()),
                ('patient_id', models.UUIDField()),
            ],
            options={
                'abstract': False,
            },
            bases=(djangoapp.common.models.GenericEntityBase, models.Model),
        ),
        migrations.CreateModel(
            name='MaterialDefectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_id', models.UUIDField()),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(djangoapp.common.models.GenericValueObjectBase, models.Model),
        ),
        migrations.CreateModel(
            name='ReferralDefectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_id', models.UUIDField()),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(djangoapp.common.models.GenericValueObjectBase, models.Model),
        ),
        migrations.CreateModel(
            name='FlaskModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('pieces_count', models.IntegerField()),
                ('pieces_count_to_work', models.IntegerField()),
                ('lifecase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flasks', to='lab.lifecasemodel')),
            ],
            options={
                'abstract': False,
            },
            bases=(djangoapp.common.models.GenericEntityBase, models.Model),
        ),
        migrations.AddField(
            model_name='lifecasemodel',
            name='material_defect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.materialdefectmodel'),
        ),
        migrations.AddField(
            model_name='lifecasemodel',
            name='referral_defect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.referraldefectmodel'),
        ),
        migrations.CreateModel(
            name='SelectedPreviousCaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.UUIDField()),
                ('lifecase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_previous_cases', to='lab.lifecasemodel')),
            ],
            options={
                'abstract': False,
            },
            bases=(djangoapp.common.models.GenericEntityBase, models.Model),
        ),
    ]
