# Generated by Django 5.0.4 on 2024-05-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdefectmodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referraldefectmodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
