# Generated by Django 5.0.4 on 2024-04-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_selectedpreviouscases_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectedPreviousCases',
            new_name='SelectedPreviousCaseModel',
        ),
    ]
